import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import * as z from 'zod';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const integrationDir = path.join(__dirname, '.integration-test');

const mcpServer = new McpServer(
  { name: 'project-management', version: '1.0.0' },
  { instructions: 'Exposes tools to verify backlog automation. Use create_user_story_fixture only for integration tests.' }
);

mcpServer.registerTool(
  'create_user_story_fixture',
  {
    description:
      'Writes a minimal user-story markdown file under mcp-project-management/.integration-test/ for MCP integration verification (not for production backlog).',
    inputSchema: {
      slug: z.string().min(1).describe('kebab-case filename segment, e.g. mcp-verify'),
      title: z.string().min(1).describe('Story title line')
    }
  },
  async ({ slug, title }) => {
    await fs.mkdir(integrationDir, { recursive: true });
    const safe = slug.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
    const filePath = path.join(integrationDir, `US-MCP-${safe}.md`);
    const body = `# User Story: US-MCP-${safe} — ${title}

**Status**: ⭕ To Do  
**Source**: Generated by MCP tool \`create_user_story_fixture\` for US-005 verification.

## Description

Integration test artifact; safe to delete after verification.
`;
    await fs.writeFile(filePath, body, 'utf8');
    return {
      content: [{ type: 'text', text: JSON.stringify({ path: filePath, repoRoot }) }]
    };
  }
);

mcpServer.registerTool(
  'pm_ping',
  {
    description: 'Health check for the project-management MCP server.',
    inputSchema: {}
  },
  async () => ({
    content: [{ type: 'text', text: 'project-management MCP server ok' }]
  })
);

async function main() {
  const transport = new StdioServerTransport();
  await mcpServer.connect(transport);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
